# instellingen.py

TITEL = "Pong"
ACHTERGROND_KLEUR = "black"
VOORGROND_KLEUR = "orange"

SCHERM_BREEDTE = 800
SCHERM_HOOGTE = 600

BATJE_STAP = 25
BATJE_HOOGTE = 5
BATJE_BREEDTE = 1

BATJE_A_X = -350
BATJE_B_X = 350

BAL_START_SNELHEID_X = 0.14
BAL_START_SNELHEID_Y = -0.14
BAL_MAX_SNELHEID = 0.45
BAL_VERSNELLING = 1.05

BOVENRAND = 280
ONDERRAND = -280

LINKS_UIT = -390
RECHTS_UIT = 390

MIDDENLIJN_AANTAL_STREPEN = 30
MIDDENLIJN_STREEP_LENGTE = 10
MIDDENLIJN_TUSSENRUIMTE = 10

LETTERTYPE = ("Press Start 2P", 20, "normal")

TOETS_A_OMHOOG = "w"
TOETS_A_OMLAAG = "s"
TOETS_B_OMHOOG = "Up"
TOETS_B_OMLAAG = "Down"